- name: Download and add SSH key to remote server
  hosts: "{{ target_group }}"
  vars:
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    local_key_path: "/tmp/{{ ssh_key_file }}"
    access_log_file: "/home/adlet-test/ssh_center_access.log"

  tasks:
    - name: Download SSH key from GitLab
      get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}"
        dest: "{{ local_key_path }}"
        mode: '0644'
      delegate_to: localhost

    - name: Read SSH public key from file and format correctly
      set_fact:
        ssh_key: "{{ lookup('file', local_key_path) | regex_replace('\\s+', ' ') }}"

    - name: Add the public SSH key to authorized_keys for root user
      authorized_key:
        user: root
        state: present
        key: "{{ ssh_key }}"
        path: "/root/.ssh/authorized_keys"
      become: yes
      become_method: sudo
      become_flags: "-i"

    - name: Log access to group(s) for {{ ssh_key_file }}
      lineinfile:
        path: "{{ access_log_file }}"
        line: "{{ ssh_key_file }} has access to {{ target_group }}"
        mode: '0644'
        state: present
      delegate_to: 172.17.3.68
      vars:
        ansible_ssh_user: adlet-test
        ansible_ssh_pass: "jhufybpfwbz"

    - name: Display access log entry for user
      debug:
        msg: "Logged access for {{ ssh_key_file }} to group {{ target_group }}"
