- name: Download and add SSH key to remote server
  hosts: "{{ target_group }}"
  vars:
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    local_key_path: "/var/tmp/{{ ssh_key_file }}"

  tasks:
    - name: Download SSH key from GitLab
      get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}"
        dest: "{{ local_key_path }}"
        mode: '0644'
      delegate_to: localhost

    - name: Read SSH public key from file and format correctly
      set_fact:
        ssh_key: "{{ lookup('file', local_key_path) | regex_replace('\\s+', ' ') }}"

    - name: Add the public SSH key to authorized_keys for root user
      authorized_key:
        user: root
        state: present
        key: "{{ ssh_key }}"
        path: "/root/.ssh/authorized_keys"
