- name: Fetch target groups and deploy SSH key
  hosts: localhost
  gather_facts: no
  vars:
    remote_host: "172.17.3.68"
    remote_user: "adlet-test"
    remote_password: "jhufybpfwbz"
    access_log_file: "/home/adlet-test/ssh_center_access.log"
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    ssh_key_file: "{{ tower_user_name }}"
    local_key_path: "/tmp/{{ ssh_key_file }}"

  tasks:
    - name: Fetch groups for current user
      ansible.builtin.shell: |
        grep {{ tower_user_name }} {{ access_log_file }} | awk '{print $NF}' | tr '\n' ',' | sed 's/,$//'
      register: user_groups
      delegate_to: "{{ remote_host }}"
      vars:
        ansible_user: "{{ remote_user }}"
        ansible_password: "{{ remote_password }}"
        ansible_become: no

    - name: Debug user groups
      ansible.builtin.debug:
        var: user_groups.stdout

    - name: Set target groups as fact
      ansible.builtin.set_fact:
        target_group: "{{ user_groups.stdout.split(',') }}"

    - name: Debug target group fact
      ansible.builtin.debug:
        var: target_group

    - name: Download SSH key from GitLab
      ansible.builtin.get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}"
        dest: "{{ local_key_path }}"
        mode: '0644'
      delegate_to: localhost

    - name: Read SSH public key from file and format correctly
      ansible.builtin.set_fact:
        ssh_key: "{{ lookup('file', local_key_path) | regex_replace('\\s+', ' ') }}"

    - name: Add the public SSH key to authorized_keys for root user on target groups
      ansible.builtin.authorized_key:
        user: root
        state: present
        key: "{{ ssh_key }}"
        path: "/root/.ssh/authorized_keys"
      become: yes
      become_method: sudo
      become_flags: "-i"
      delegate_to: "{{ item }}"
      with_items: "{{ target_group }}"
