---
- name: Determine target groups from access log
  hosts: localhost
  gather_facts: no
  vars:
    access_log_file: "/home/adlet-test/ssh_center_access.log"
    ssh_key_file: "{{ tower_user_name }}"

  tasks:
    - name: Read access log and get user's groups
      command: "grep {{ ssh_key_file }} {{ access_log_file }}"
      register: access_log_output
      delegate_to: 172.17.3.68
      vars:
        ansible_ssh_user: adlet-test
        ansible_ssh_pass: "jhufybpfwbz"
      changed_when: false

    - name: Extract target groups
      set_fact:
        target_groups: "{{ access_log_output.stdout | regex_findall('has access to (\\S+)') }}"

    - name: Debug target groups
      debug:
        var: target_groups

- name: Deploy SSH key to authorized servers
  hosts: "{{ target_groups }}"
  gather_facts: no
  vars:
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    ssh_key_file: "{{ tower_user_name }}"  
    local_key_path: "/tmp/{{ ssh_key_file }}"

  tasks:
    - name: Download SSH key from GitLab
      get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}"
        dest: "{{ local_key_path }}"
        mode: '0644'
      delegate_to: localhost

    - name: Read SSH public key from file and format correctly
      set_fact:
        ssh_key: "{{ lookup('file', local_key_path) | regex_replace('\\s+', ' ') }}"

    - name: Add the public SSH key to authorized_keys for root user
      authorized_key:
        user: root
        state: present
        key: "{{ ssh_key }}"
        path: "/root/.ssh/authorized_keys"
      become: yes
