- name: Get target groups from log file
  hosts: localhost
  gather_facts: no
  vars:
    remote_host: "172.17.3.68"
    remote_user: "adlet-test"
    remote_password: "jhufybpfwbz"
    access_log_file: "/home/adlet-test/ssh_center_access.log"

  tasks:
    - name: Fetch groups for current user
      ansible.builtin.shell: |
        grep {{ tower_user_name }} {{ access_log_file }} | awk '{print $NF}' | tr '\n' ',' | sed 's/,$//'
      register: user_groups
      delegate_to: "{{ remote_host }}"
      vars:
        ansible_user: "{{ remote_user }}"
        ansible_password: "{{ remote_password }}"
        ansible_become: no

    - name: Set user groups as fact
      ansible.builtin.set_fact:
        target_groups: "{{ user_groups.stdout.split(',') }}"

- name: Add SSH key to target groups
  hosts: "{{ target_groups }}"
  gather_facts: no
  vars:
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    ssh_key_file: "{{ tower_user_name }}"
  tasks:
    - name: Download SSH key
      ansible.builtin.get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}.pub"
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        mode: '0600'
