---
- name: Deploy SSH key to allowed servers based on access log
  hosts: localhost
  vars:
    ssh_key_repo: "https://gitlab.cl.nat.kz/adilet.jarassov/ssh-public-keys-storage/raw/main"
    ssh_key_file: "{{ tower_user_name }}"  # Имя файла по логину в AWX
    local_key_path: "/tmp/{{ ssh_key_file }}"
    access_log_file: "/home/adlet-test/ssh_center_access.log"

  tasks:
    - name: Get user access info from the log
      command: "grep '{{ ssh_key_file }} has access to' {{ access_log_file }}"
      delegate_to: 172.17.3.68
      register: access_info
      changed_when: false
      vars:
        ansible_ssh_user: adlet-test
        ansible_ssh_pass: "jhufybpfwbz"

    - name: Extract target groups from access log
      set_fact:
        target_groups: "{{ access_info.stdout_lines | map('regex_replace', '.*has access to (.+)', '\\1') | list }}"

    - name: Fail if no access groups found
      fail:
        msg: "No access groups found for user {{ ssh_key_file }}"
      when: target_groups | length == 0

    - name: Display target groups
      debug:
        msg: "User {{ ssh_key_file }} has access to the following groups: {{ target_groups | join(', ') }}"

    - name: Download SSH key from GitLab
      get_url:
        url: "{{ ssh_key_repo }}/{{ ssh_key_file }}"
        dest: "{{ local_key_path }}"
        mode: '0644'
      delegate_to: localhost

    - name: Read SSH public key from file
      set_fact:
        ssh_key: "{{ lookup('file', local_key_path) | regex_replace('\\s+', ' ') }}"

    - name: Deploy SSH key to authorized servers
      include_tasks: deploy_key.yml
      loop: "{{ target_groups }}"
      loop_control:
        loop_var: target_group

- name: Deploy SSH key
  hosts: "{{ target_group }}"
  tasks:
    - name: Ensure the .ssh directory exists
      file:
        path: "/root/.ssh"
        state: directory
        mode: '0700'
      become: yes

    - name: Add the public SSH key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ ssh_key }}"
        path: "/root/.ssh/authorized_keys"
      become: yes

    - name: Confirm key deployment
      debug:
        msg: "SSH key for {{ ssh_key_file }} successfully added to {{ target_group }}"
