---
- name: Manage SSH key in GitLab repository
  hosts: localhost
  vars:
    gitlab_api_url: "https://gitlab.cl.nat.kz/api/v4/projects/619/repository/files"
    gitlab_token: "ds_Nk5gA8AkB_XL3YtUM"
    ssh_key: "{{ ssh_key_content }}"
    ssh_key_file: "{{ tower_user_name }}"
    branch: "main"
    commit_message: "Add or update SSH key for {{ tower_user_name }}"

  tasks:
    - name: Check if SSH key file exists in GitLab
      uri:
        url: "{{ gitlab_api_url }}/{{ ssh_key_file | urlencode }}?ref={{ branch }}"
        method: "GET"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_token }}"
        status_code: [200, 404]
      register: check_key_result

    - name: Create SSH key if it does not exist
      uri:
        url: "{{ gitlab_api_url }}/{{ ssh_key_file | urlencode }}"
        method: "POST"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_token }}"
        body_format: "json"
        body:
          branch: "{{ branch }}"
          content: "{{ ssh_key }}"
          commit_message: "Add SSH key for {{ tower_user_name }}"
          encoding: "text"
        status_code: [201]
      when: check_key_result.status == 404
      register: add_key_result

    - name: Update SSH key if it already exists
      uri:
        url: "{{ gitlab_api_url }}/{{ ssh_key_file | urlencode }}"
        method: "PUT"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_token }}"
        body_format: "json"
        body:
          branch: "{{ branch }}"
          content: "{{ ssh_key }}"
          commit_message: "Update SSH key for {{ tower_user_name }}"
          encoding: "text"
        status_code: [200]
      when: check_key_result.status == 200
      register: update_key_result

    - name: Show message when SSH key is created
      debug:
        msg: " Ваш SSH-ключ успешно добавлен в репозиторий GitLab!"
      when: add_key_result is succeeded

    - name: Show message when SSH key is updated
      debug:
        msg: " Ваш SSH-ключ успешно обновлён в репозитории GitLab!"
      when: update_key_result is succeeded
