- name: Установка и обновление конфигурации Zabbix Agent
  hosts: "{{ target_group }}"
  become: yes

  tasks:
    - name: Установить Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Убедиться, что Zabbix Agent запущен
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Изменить строку Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=172.17.3.68'
        state: present
        backup: yes

    - name: Изменить строку ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=172.17.3.68'
        state: present
        backup: yes

    - name: Изменить или добавить Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^(#\s*)?Hostname='
        line: 'Hostname={{ inventory_hostname }}'
        state: present
        create: yes
        backup: yes

    - name: Добавить HostMetadata
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^#? HostMetadata='
        line: 'HostMetadata={{ host_metadata }}'
        state: present
        backup: yes

    - name: Перезапустить Zabbix Agent
      systemd:
        name: zabbix-agent
        state: restarted
